name: on branch push

on:
  pull_request:
  push:
    branches:
      - main
      - develop

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dafnik/setup-node-pnpm@v5
        with:
          install-ignore-scripts: true

      - name: Style check
        run: pnpm format:check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dafnik/setup-node-pnpm@v5
        with:
          install-ignore-scripts: true

      - name: ESLint
        run: pnpm lint

  commitlint:
    name: Commitlint Check
    runs-on: ubuntu-latest
    steps:
      # Needed to get the commitlint config
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Commit lint
        uses: dafnik/commitlint@v1

  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v7

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v5
        with:
          install-ignore-scripts: true

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: test
        shell: bash
        run: pnpm test

  build-libs:
    name: Build libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v5
        with:
          install-ignore-scripts: true

      - name: build
        run: pnpm build

  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v5
        with:
          install-ignore-scripts: true

      - name: build docs
        run: pnpm -C apps/docs build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./apps/docs/dist/
          retention-days: 1

  deploy-docs:
    if: github.ref == 'refs/heads/main'
    name: Deploy docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      actions: read
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
