name: release @qrcodesdk/node

on:
  push:
    tags:
      - '@qrcodesdk/node@**'

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for GitHub release action

jobs:
  node:
    uses: ./.github/workflows/release.yml
    with:
      lib: node
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
